version: "3.1"

# TODO: manually test with at least web-portal

services:
#  nginx-router:
#    networks: { default: { aliases: [ 'zorko-io.local' ] } }
#    build: { context: ./dev-ops/nginx-router}
#    restart: always
#    ports: ['80:80']
  web-portal:
    networks: { default: { aliases: [ 'zorko-io.backend' ] } }
    build: dev-ops/common
    restart: always
    ports: ['7777:7777', '9229:9229']
