version: "3.1"

services:
  nginx-router:
    networks: { default: { aliases: [ 'zorko-io.local' ] } }
    build: { context: ./dev-ops/nginx-router}
    restart: always
    ports: ['80:80']
    depends_on:
      - web-portal
      - web-portal-client
    volumes:
      - ./dev-ops/nginx-router/conf.d:/etc/nginx/conf.d
  web-portal:
    networks: { default: { aliases: [ 'zorko-io.backend' ] } }
    build: { context: ./dev-ops/common}
    restart: always
    command: sh -c "cd ./apps/web-portal && yarn run start:debug"
    ports: ['7777:7777', '9229:9229']
    working_dir: /zorko-platform
    volumes:
      - ./:/zorko-platform
  web-portal-client:
    networks: { default: { aliases: [ 'zorko-io.frontend' ] } }
    build: { context: ./dev-ops/common}
    restart: always
    command: sh -c "cd ./apps/web-portal-client && yarn run start"
    ports: ['8086:8086']
    working_dir: /zorko-platform
    volumes:
      - ./:/zorko-platform
