version: "3.1"

# TODO: manually test with at least web-portal

services:
# TODO: configure networks https://codingwithmanny.medium.com/create-an-nginx-reverse-proxy-with-docker-a1c0aa9078f1
#  nginx-router:
#    networks: { default: { aliases: [ 'zorko-io.local' ] } }
#    build: { context: ./dev-ops/nginx-router}
#    restart: always
#    ports: ['80:80']
  web-portal:
    networks: { default: { aliases: [ 'zorko-io.backend' ] } }
    image: zorko-common
    restart: always
    command: sh -c "cd ./apps/web-portal && yarn run start:debug"
    ports: ['7777:7777', '9229:9229']
    working_dir: /zorko-platform
    volumes:
      - ./:/zorko-platform
  web-portal-client:
    networks: { default: { aliases: [ 'zorko-io.frontend' ] } }
    image: zorko-common
    restart: always
    command: sh -c "cd ./apps/web-portal-client && yarn run start"
    ports: ['8086:8086']
    working_dir: /zorko-platform
    volumes:
      - ./:/zorko-platform
