#!/usr/bin/env groovy

pipeline {
    agent {
        docker {
          image 'node:14-alpine'
        }
    }
    stages {
        stage('Check Env') {
            steps {
                sh 'node --version'
                sh 'yarn --version'

            }
        }
    }
}

