#!/usr/bin/env groovy

pipeline {
    agent {
        docker {
          image 'node:14-alpine'
        }
    }
    stages {
        stage('Check Env') {
            steps {
                sh 'node --version'
                sh 'yarn --version'

            }
        }
        stage('Install Deps') {
            steps {
                sh 'yarn'

            }
        }
        stage('Static Code Analysis') {
            steps {
                echo 'yarn run code'

            }
        }
        stage('Tests') {
            steps {
                sh 'yarn test:coverage'
            }
            post {
              success {
                // publish html
                publishHTML target: [
                    allowMissing: false,
                    alwaysLinkToLastBuild: false,
                    keepAll: true,
                    reportDir: 'packages/util-validation/coverage',
                    reportFiles: 'index.html',
                    reportName: 'Coverage Report',
                  ]
              }
            }
        }
    }
}

