name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [ 14 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Cypress run
        run: yarn cy:ci