name: Test Publish to Github PKG
# Temp for testing proposes
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          IMG_TAG: nesterone/zorko-standalone:sha-${{ github.sha }}
        with:
          context: ./
          file: ./dev-ops/release/Dockerfile
          push: true
          target: standalone
          tags: ${{ env.IMG_TAG }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
